version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env  # 환경 변수 파일 추가
    depends_on:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads  # 업로드 디렉토리 마운트
      - ./zips:/usr/src/app/zips  # ZIP 파일 생성 디렉토리 마운트

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
