version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    environment:
      - TZ=Asia/Seoul
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./zips:/usr/src/app/zips
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;"]
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
